export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const GET_ARTWORKS_BEGIN = "GET_ARTWORKS_BEGIN";
export const GET_ARTWORKS_SUCCESS = "GET_ARTWORKS_SUCCESS";
export const GET_ARTWORKS_ERROR = "GET_ARTWORKS_ERROR";
export const GET_SINGLE_ARTWORK_BEGIN = "GET_SINGLE_ARTWORK_BEGIN";
export const GET_SINGLE_ARTWORK_SUCCESS = "GET_SINGLE_ARTWORK_SUCCESS";
export const GET_SINGLE_ARTWORK_ERROR = "GET_SINGLE_ARTWORK_ERROR";

export const FETCH_ARTISTS_SUCCESS = "FETCH_ARTISTS_SUCCESS";

export const SET_LOADING = "SET_LOADING";

export const GET_USER_LIKED_ARTWORKS = "GET_USER_LIKED_ARTWORKS";

export const GET_USER_FOLLOWED_ARTIST = "GET_USER_FOLLOWED_ARTIST";

export const FOLLOW_ARTIST_SUCCESS = "FOLLOW_ARTIST_SUCCESS";
export const UNFOLLOW_ARTIST_SUCCESS = "UNFOLLOW_ARTIST_SUCCESS";

export const UPDATE_USER_LIKED_ARTWORKS = "UPDATE_USER_LIKED_ARTWORKS";
export const UPDATE_ARTWORK_LIKES = "UPDATE_ARTWORK_LIKES";

export const UPDATE_LIKES_SUCCESS = "UPDATE_LIKES_SUCCESS";
export const UPDATE_LIKES_ERROR = "UPDATE_LIKES_ERROR";

export const GET_REVIEWS_BEGIN = "GET_REVIEWS_BEGIN";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_ERROR = "GET_REVIEWS_ERROR";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR";

export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const CREATE_ART_SUCCESS = "CREATE_ART_SUCCESS";
export const CREATE_ART_ERROR = "CREATE_ART_ERROR";
export const DELETE_ART_ERROR = "DELETE_ART_ERROR";
export const FETCH_SINGLE_ART_SUCCESS = "FETCH_SINGLE_ART_SUCCESS";
export const FETCH_SINGLE_ART_ERROR = "FETCH_SINGLE_ART_ERROR";

export const EDIT_ART_SUCCESS = "EDIT_ART_SUCCESS";
export const EDIT_ART_ERROR = "EDIT_ART_ERROR";
